export const JapanNames = [
    {
        id:1,
        firstName:"Ritsu",
        lastName:"Dohan",
    },
    {
        id:2,
        firstName:"Ao",
        lastName:"Tanaka",
    },
    {
        id:3,
        firstName:"Ko",
        lastName:"Itakura",
    },
    {
        id:4,
        firstName:"Kaoru",
        lastName:"Mitoma",
    },
    {
        id:5,
        firstName:"Hiroki",
        lastName:"Sakai",
    },
    {
        id:6,
        firstName:"Maya",
        lastName:"Yoshida",
    },
    {
        id:7,
        firstName:"Junya",
        lastName:"Ito",
    },
    {
        id:8,
        firstName:"Miki",
        lastName:"Yamane",
    },
    {
        id:9,
        firstName:"Shogo",
        lastName:"Taniguchi",
    },
    {
        id:10,
        firstName:"Shuichi ",
        lastName:"Gonda",
    },
    {
        id:11,
        firstName:"Wataru",
        lastName:"Endo",
    },
]
 Szczesny

export const PolandNames = [
    {
        id:1,
        firstName:"Wojciech",
        lastName:"Szczesny",
    },
    {
        id:2,
        firstName:"Robert",
        lastName:"Lewandowski",
    },
    {
        id:3,
        firstName:"Piotr",
        lastName:"Zielinski",
    },
    {
        id:4,
        firstName:"Grzegorz",
        lastName:"Krychowiak",
    },
    {
        id:5,
        firstName:"Karol",
        lastName:"Swiderksi",
    },
    {
        id:6,
        firstName:"Krystian",
        lastName:"Bielik",
    },
    {
        id:7,
        firstName:"Przemyslaw",
        lastName:"Frankowski",
    },
    {
        id:8,
        firstName:"Sebastian",
        lastName:"Szymanski",
    },
    {
        id:9,
        firstName:"Kamil",
        lastName:"Glik",
    },
    {
        id:10,
        firstName:"Bartosz",
        lastName:" Bereszynski",
    },
    {
        id:11,
        firstName:"Jakub",
        lastName:"Kiwior",
    },
]